PubkeyAuthentication yes
AuthenticationMethods publickey

PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no

UsePAM yes

StrictModes yes

LoginGraceTime 30
MaxAuthTries 4

X11Forwarding no
PermitTunnel no
PermitUserEnvironment no

AllowGroups ssh-users
PermitRootLogin no

LogLevel VERBOSE
